export const OPPORTUNITY_THRESHOLDS = {
  CONCENTRATION_SHARE: Number(process.env.OPP_CONCENTRATION_SHARE ?? 0.5),
  TREND_INCREASE: Number(process.env.OPP_TREND_INCREASE ?? 0.2),
  TREND_WINDOW_DAYS: Number(process.env.OPP_TREND_WINDOW_DAYS ?? 30),
  ANOMALY_STD_FACTOR: Number(process.env.OPP_ANOMALY_STD_FACTOR ?? 3),
  ANOMALY_MIN_SAMPLE: Number(process.env.OPP_ANOMALY_MIN_SAMPLE ?? 5),
  STEEL_TON_THRESHOLD: Number(process.env.OPP_STEEL_TON_THRESHOLD ?? 10),
} as const;
